version: "3.7"
services:
  api_service:
    build: .
    hostname: api_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
  mysql_db:
    image: "mysql"
    hostname: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: share_us_db
      MYSQL_ROOT_PASSWORD: root

